# -*- coding: utf-8 -*-
"""1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oOWsVCNwdmEeY5wqZzcEQT555P5jDZa8
"""

import re
def validate_contact_number(number):
    pattern = r'^(\+\d{1,2})?[-.\s]?(\d{1,4})[-.\s]?(\d{1,4})[-.\s]?(\d{4})$'
    if re.match(pattern, number):
        return True
    else:
        return False
numbers = [
    "2124567890",
    "212-456-7890",
    "(212)456-7890",
    "(212)-456-7890",
    "212.456.7890",
    "212 456 7890",
    "+12124567890",
    "+1 212.456.7890",
    "+212-456-7890",
    "1-212-456-7890"
]
for number in numbers:
    if validate_contact_number(number):
        print(f"{number} is a valid contact number.")
    else:
        print(f"{number} is an invalid contact number.")